#!/bin/bash
set -euo pipefail
if ! [ -x .venv/bin/black ] || ! [ -x .venv/bin/isort ] ; then
	echo "Please install black and isort in .venv/bin by running python3 -m venv .venv && .venv/bin/pip install -r requirements.txt"
	exit
fi
scripts/git-format-staged -f 'isort -q - | black -q -' '*.py'
