# Generated by Django 3.1.2 on 2020-11-01 13:02

import re

import django.core.validators
import django.db.models.deletion
import votee.crypto
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Election",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                (
                    "slug",
                    models.SlugField(
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                re.compile("^[-\\w]+\\Z"),
                                "Enter a valid “slug” consisting of Unicode letters, numbers, underscores, or hyphens.",
                                "invalid",
                            )
                        ],
                    ),
                ),
                (
                    "admin_secret",
                    models.BinaryField(default=votee.crypto.rand128, max_length=16),
                ),
                ("settings_raw", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Poll",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                (
                    "slug",
                    models.SlugField(
                        validators=[
                            django.core.validators.RegexValidator(
                                re.compile("^[-\\w]+\\Z"),
                                "Enter a valid “slug” consisting of Unicode letters, numbers, underscores, or hyphens.",
                                "invalid",
                            )
                        ]
                    ),
                ),
                ("settings_raw", models.TextField()),
                (
                    "ballot_secret",
                    models.BinaryField(default=votee.crypto.rand128, max_length=16),
                ),
                ("number_of_ballots", models.IntegerField(default=0)),
                (
                    "election",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="votee.election"
                    ),
                ),
            ],
            options={
                "unique_together": {("election", "slug")},
            },
        ),
        migrations.CreateModel(
            name="PollOption",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(blank=True)),
                ("count", models.IntegerField(default=0)),
                (
                    "poll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="votee.poll"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UsedBallot",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ballot_index", models.IntegerField()),
                (
                    "poll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="votee.poll"
                    ),
                ),
            ],
            options={
                "unique_together": {("poll", "ballot_index")},
            },
        ),
    ]
